export {
  createDatabaseConnection,
  type Database,
  type DatabaseConnection,
} from "./client.js";
export { migrateDatabase } from "./migration-runner.js";
export {
  accounts,
  auditEvents,
  boards,
  boardControllerLeases,
  competitions,
  competitionSlots,
  legs,
  encounterCommands,
  encounterLineupEntries,
  encounterNominations,
  encounterSlots,
  encounterSubstitutions,
  encounters,
  matches,
  matchParticipantPlayers,
  matchParticipants,
  memberships,
  organizationInvitations,
  organizations,
  outboxEvents,
  playerStatisticAggregates,
  players,
  sessions,
  teamPlayers,
  teams,
  scoreCommands,
  tournamentBoards,
  tournamentCommands,
  tournamentGroupParticipants,
  tournamentGroups,
  tournamentMatches,
  tournamentParticipants,
  tournaments,
  tournamentStages,
  users,
  visits,
  verifications,
  type Account,
  type AuditEvent,
  type Board,
  type BoardControllerLease,
  type Competition,
  type CompetitionSlot,
  type Leg,
  type Encounter,
  type EncounterCommand,
  type EncounterLineupEntry,
  type EncounterNomination,
  type EncounterSlot,
  type EncounterSubstitution,
  type Match,
  type MatchParticipant,
  type Membership,
  type NewAccount,
  type NewCompetition,
  type NewCompetitionSlot,
  type NewEncounter,
  type NewEncounterLineupEntry,
  type NewEncounterNomination,
  type NewEncounterSlot,
  type NewEncounterSubstitution,
  type NewAuditEvent,
  type NewMembership,
  type NewOrganization,
  type NewOrganizationInvitation,
  type NewPlayer,
  type NewTeam,
  type NewTeamPlayer,
  type NewSession,
  type NewUser,
  type NewVerification,
  type Organization,
  type OrganizationInvitation,
  type OutboxEvent,
  type PlayerStatisticAggregate,
  type Player,
  type Session,
  type Team,
  type TeamPlayer,
  type ScoreCommand,
  type Tournament,
  type TournamentBoard,
  type TournamentCommand,
  type TournamentGroup,
  type TournamentGroupParticipant,
  type TournamentMatch,
  type TournamentParticipant,
  type TournamentStage,
  type User,
  type Visit,
  type Verification,
} from "./schema.js";
